### ISSUE TITLE
add back in filter

### ISSUE THREAD

**Issue by aishahnazar** [missfits/Robot-Code-2024#20]
https://github.com/missfits/Robot-Code-2024/blame/893de6cd5e4543bee4cd5c99a7424c3df866b5d6/src/main/java/frc/robot/commands/ArcadeDriveCommand.java#L30C12-L30C18 

In the repo, in the arcadedrivecommand file, there is a variable called filter which is defined but later it was temporarily commented; we should add filter back in 

@amzoeee

**Comment by amzoeee** [comment]
This filter is a slew rate limiter that we tried on the robot in order to prevent our earlier tipping. It made the robot significantly less responsive, so we never ended up using this filter.
